name = "frontend-check-bot"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "frontend-check-bot-db"
database_id = "944f76c6-ab60-4601-a23f-ba8b2bff246f"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "6dc414697cb440a5b657481ecdac3118"
