main = ".worker-next/index.mjs"
name = "frontend-check-bot"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "frontend-check-bot-db"
database_id = "944f76c6-ab60-4601-a23f-ba8b2bff246f"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "6dc414697cb440a5b657481ecdac3118"
